//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamBotAuthFileGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamBotAuthFileGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Form1_button_generate_Click_Error {
            get {
                return ResourceManager.GetString("Form1_button_generate_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in: .
        /// </summary>
        internal static string Form1_button_generate_Click_Error_logging_in__ {
            get {
                return ResourceManager.GetString("Form1_button_generate_Click_Error_logging_in__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        internal static string Form1_button_generate_Click_Generating___ {
            get {
                return ResourceManager.GetString("Form1_button_generate_Click_Generating___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Form1_button_generate_Click_Success {
            get {
                return ResourceManager.GetString("Form1_button_generate_Click_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully generated your auth file!.
        /// </summary>
        internal static string Form1_button_generate_Click_Successfully_generated_your_auth_file_ {
            get {
                return ResourceManager.GetString("Form1_button_generate_Click_Successfully_generated_your_auth_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not appear to have 2FA enabled. Login result: .
        /// </summary>
        internal static string Form1_button_generate_Click_This_account_does_not_appear_to_have_2FA_enabled__Login_result__ {
            get {
                return ResourceManager.GetString("Form1_button_generate_Click_This_account_does_not_appear_to_have_2FA_enabled__Log" +
                        "in_result__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Form1_ResetGenerateButton_Generate {
            get {
                return ResourceManager.GetString("Form1_ResetGenerateButton_Generate", resourceCulture);
            }
        }
    }
}
